In [3]:
%pip install -q ipytest pytest 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: C:\Users\asdsf\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [4]:
import ipytest
import pytest

ipytest.autoconfig()

In [5]:
%pip install -Uq numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: C:\Users\asdsf\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [6]:
import numpy as np

In [12]:
class Matrix:
    def __init__(self, matrix):
        self.matrix = matrix

    def __add__(self, other):
        if isinstance(other, Matrix):
            if len(self.matrix) == len(other.matrix) and len(self.matrix[0]) == len(other.matrix[0]):
                result = [[0] * len(self.matrix[0]) for _ in range(len(self.matrix))]
                for i in range(len(self.matrix)):
                    for j in range(len(self.matrix[0])):
                        result[i][j] = self.matrix[i][j] + other.matrix[i][j]
                return Matrix(result)
            else:
                raise ValueError("Размерности матриц не совпадают")
        elif isinstance(other, (int, float)):
            result = [[0] * len(self.matrix[0]) for _ in range(len(self.matrix))]
            for i in range(len(self.matrix)):
                for j in range(len(self.matrix[0])):
                    result[i][j] = self.matrix[i][j] + other
            return Matrix(result)
        else:
            raise TypeError("Аргумент должен быть объектом класса Matrix, int или float")

    def __sub__(self, other):
        if isinstance(other, Matrix):
            if len(self.matrix) == len(other.matrix) and len(self.matrix[0]) == len(other.matrix[0]):
                result = [[0] * len(self.matrix[0]) for _ in range(len(self.matrix))]
                for i in range(len(self.matrix)):
                    for j in range(len(self.matrix[0])):
                        result[i][j] = self.matrix[i][j] - other.matrix[i][j]
                return Matrix(result)
            else:
                raise ValueError("Размерности матриц не совпадают")
        elif isinstance(other, (int, float)):
            result = [[0] * len(self.matrix[0]) for _ in range(len(self.matrix))]
            for i in range(len(self.matrix)):
                for j in range(len(self.matrix[0])):
                    result[i][j] = self.matrix[i][j] - other
            return Matrix(result)
        else:
            raise TypeError("Аргумент должен быть объектом класса Matrix, int или float")

    def __repr__(self):
        return repr(self.matrix)

    def __matmul__(self, other):
        if isinstance(other, (int, float)):
            result = [[0] * len(self.matrix[0]) for _ in range(len(self.matrix))]
            for i in range(len(self.matrix)):
                for j in range(len(self.matrix[0])):
                    result[i][j] = self.matrix[i][j] * other
            return Matrix(result)
        
        elif isinstance(other, Matrix):
            if len(self.matrix[0]) == len(other.matrix):
                result = [[0] * len(other.matrix[0]) for _ in range(len(self.matrix))]

                for i in range(len(self.matrix)):
                    for j in range(len(other.matrix[0])):
                        for k in range(len(other.matrix)):

                            result[i][j] += self.matrix[i][k] * other.matrix[k][j]

                return Matrix(result)
            
            else:
                raise ValueError("Количество столбцов первой матрицы не совпадает с количеством строк второй матрицы")
            
        else:
            raise TypeError("Аргумент должен быть числом или объектом класса Matrix")

    def __truediv__(self, other):
        if isinstance(other, Matrix):
            
            if len(self.matrix) != len(other.matrix) or len(self.matrix[0]) != len(other.matrix[0]):
                raise ValueError("Несовместимые размеры матриц")

            result = [[0 for _ in range(len(self.matrix[0]))] for _ in range(len(self.matrix))]

            for i in range(len(self.matrix)):
                for j in range(len(self.matrix[0])):
                    result[i][j] = self.matrix[i][j] / other.matrix[i][j]

            return Matrix(result)

        elif isinstance(other, (int, float)):
            result = [[0 for _ in range(len(self.matrix[0]))] for _ in range(len(self.matrix))]

            for i in range(len(self.matrix)):
                for j in range(len(self.matrix[0])):
                    result[i][j] = self.matrix[i][j] / other

            return Matrix(result)

        else:
            raise ValueError("Аргумент должен быть объектом класса Matrix или числом")
        

    def __mul__(self, other):
        if isinstance(other, Matrix):
            
            if len(self.matrix) != len(other.matrix) or len(self.matrix[0]) != len(other.matrix[0]):
                raise ValueError("Несовместимые размеры матриц")

            result = [[0 for _ in range(len(self.matrix[0]))] for _ in range(len(self.matrix))]

            for i in range(len(self.matrix)):
                for j in range(len(self.matrix[0])):
                    result[i][j] = self.matrix[i][j] * other.matrix[i][j]

            return Matrix(result)

        elif isinstance(other, (int, float)):
            result = [[0 for _ in range(len(self.matrix[0]))] for _ in range(len(self.matrix))]

            for i in range(len(self.matrix)):
                for j in range(len(self.matrix[0])):
                    result[i][j] = self.matrix[i][j] * other

            return Matrix(result)

        else:
            raise ValueError("Аргумент должен быть объектом класса Matrix или числом")
        
    def T(self):
        _len = len(self.matrix)
        t_matrix = [[0 for i in range(_len)] for i in range(_len)]

        for i in range(_len):
            for j in range(_len):
                t_matrix[j][i] = self.matrix[i][j]

        return Matrix(t_matrix)

    def get_dimensions(self):
        rows = len(self.matrix)
        columns = len(self.matrix[0]) if rows > 0 else 0
        return rows, columns     

    def __eq__(self, other):
        result_matrix = []
        
        for i in range(len(self.matrix)):
            row = []
            for j in range(len(self.matrix[0])):
                row.append((self.matrix[i][j]) == (other.matrix[i][j]))
            result_matrix.append(row)
        return Matrix(result_matrix)
    
    @staticmethod
    
    @staticmethod
    def gram_schmidth(self):
         
        vector_1 : list
        vector_2 : list
        vector_3 : list
        vector_4 : list

        if self.get_dimensions()[0] == 4 and self.get_dimensions()[1] == 4:
            num_columns = len(self.matrix[0])

# Создание пустого списка для векторов по столбцам
            column_vectors = [[] for _ in range(num_columns)]

# Разложение матрицы на векторы по столбцам
            for row in self.matrix:
                for i, value in enumerate(row):
                    column_vectors[i].append(value)

        # Вывод полученных векторов
        
        
            vector_1 = column_vectors[0]
            vector_2 = column_vectors[1]
            vector_3 = column_vectors[2]
            vector_4 = column_vectors[3]

            func_1 = vector_1

            func_2 = (Matrix(vector_2) - (Matrix(func_1) * (Matrix.vector_multiply(func_1,func_1) / Matrix.vector_multiply(func_1,func_1)))).matrix

            func_3 = (Matrix(vector_3) - (Matrix(func_1) * (Matrix.vector_multiply(vector_3,func_1) / Matrix.vector_multiply(func_1,func_1))) -
                               (Matrix(func_2) * (Matrix.vector_multiply(vector_3,func_2) / Matrix.vector_multiply(func_2,func_2)))).matrix
            
            func_4 = (Matrix(vector_4) - (Matrix(func_1) * (Matrix.vector_multiply(vector_4,func_1) / Matrix.vector_multiply(func_1,func_1))) -
                               (Matrix(func_2) * (Matrix.vector_multiply(vector_4,func_2) / Matrix.vector_multiply(func_2,func_2))) -
                               (Matrix(func_3) * (Matrix.vector_multiply(vector_4,func_3) / Matrix.vector_multiply(func_3,func_3)))).matrix
            return Matrix(func_1), Matrix(func_2), Matrix(func_3), Matrix(func_4)
        
        else: 
            raise AttributeError('Только матрицы 4х4')

    @staticmethod
    def norm(vector):
        result = vector.matrix[0][0] ** 2 + vector.matrix[0][1] ** 2 + vector.matrix[0][2] ** 2 + vector.matrix[0][3] ** 2
        return result ** 0.5
    
    
    def ortohonalize(self):
        if self.get_dimensions()[0] == 4 and self.get_dimensions()[1] == 4:
            res = []
            for func in self.gram_schmidth():
                res.append((func/Matrix.norm(func)).matrix)
                return(res)
        else:
            raise AttributeError("Only works with 4x4 matrixes!")
    



In [14]:
%%ipytest

matrix1 = Matrix([[1,2,3],[3,4,5],[6,7,8]])
matrix2 = Matrix([[1,2,3],[3,5,6],[7,8,9]])



@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_add_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 + matrix2).matrix) == (np.array(matrix1.matrix) + np.array(matrix2.matrix))).all()
    ), 'add section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13.2]])
def test_matrix_add_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 + number).matrix) == np.array(matrix1.matrix) + number).all()
    ), 'add section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_sub_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 - matrix2).matrix) == np.array(matrix1.matrix) - np.array(matrix2.matrix)).all()
    ), 'sub section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 12.2]])    
def test_matrix_sub_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 - number).matrix) == np.array(matrix1.matrix) - number).all()
    ), 'sub section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1", [matrix1])    
def test_matrix_transpose(matrix1: Matrix):
    assert (
        (np.array(matrix1.T().matrix) == np.array(matrix1.matrix).T).all()
    ), 'transpose section is not working right'
    
# -----------------------------------------

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])
def test_matrix_mul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 * matrix2).matrix) == np.array(matrix1.matrix) * np.array(matrix2.matrix)).all()
    ), 'mul section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 13]])
def test_matrix_mul_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 * number).matrix) == np.array(matrix1.matrix) * number).all()
    ), 'mul section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2]])    
def test_matrix_div_matrix(matrix1: Matrix, matrix2: Matrix):
    assert (
        (np.array((matrix1 / matrix2).matrix) == np.array(matrix1.matrix) / np.array(matrix2.matrix)).all()
    ), 'div section with matrices is not working right'

@pytest.mark.parametrize("matrix1,number", [[matrix1, 2]])    
def test_matrix_div_number(matrix1: Matrix, number: int | float):
    assert (
        (np.array((matrix1 / number).matrix) == np.array(matrix1.matrix) / number).all()
    ), 'div section with matrix and number is not working right'

@pytest.mark.parametrize("matrix1,matrix2", [[matrix1, matrix2.T()]])    
def test_matrix_matmul_matrix(matrix1: Matrix, matrix2: Matrix):
    assert(
        (np.array((matrix1 @ matrix2).matrix) == np.array(matrix1.matrix) @ np.array(matrix2.matrix)).all()
    ), 'matmul section is not working right, and don\'t forget about T() if needed'


..........                                                                                   [100%]
10 passed in 0.03s


In [9]:
matrix1 = Matrix([[1,2,3],[3,4,5],[5,6,7]])
matrix2 = Matrix([[1,2,3],[2,4,5],[3,6,7]])
matrix3 = Matrix([[1,2,3],[4,5,6]])

matrix4 = Matrix([[1,2],[3,4]])
matrix5 = Matrix([[2,3],[4,5]])


true_div = matrix4 / matrix5
matmul = matrix1 @ matrix2
mul = matrix4 * matrix5
sum = matrix1 + matrix2

print(true_div)
print("-----------------")
print(matmul)
print("-----------------")
print(mul)
print("-----------------")
print(matrix3.T())
print("-----------------")
print(sum)




[[10, 13], [22, 29]]
-----------------
[[14, 28, 34], [26, 52, 64], [38, 76, 94]]
-----------------
[[2, 6], [12, 20]]
-----------------
[[1, 4], [2, 5]]
-----------------
[[2, 4, 6], [5, 8, 10], [8, 12, 14]]


In [10]:
matrix1 = Matrix([[1, 2, 3],[3, 4, 5],[1, 2, 3]])
matrix2 = Matrix([[1, 2, 3],[3, 5, 6],[1, 2, 3]])
res = matrix1 @ matrix2 
print(matrix1.T())

print((np.array(matrix1.matrix) @ np.array(matrix2.matrix)))
print(res)

[[1, 3, 1], [2, 4, 2], [3, 5, 3]]
[[10 18 24]
 [20 36 48]
 [10 18 24]]
[[10, 18, 24], [20, 36, 48], [10, 18, 24]]


In [11]:
print(np.array(matrix1.matrix) * np.array(matrix2.matrix))
print(np.array(matrix1.matrix) @ np.array(matrix2.matrix))
print((matrix1 * matrix2).matrix)
print((matrix1 @ matrix2))

[[ 1  4  9]
 [ 9 20 30]
 [ 1  4  9]]
[[10 18 24]
 [20 36 48]
 [10 18 24]]
[[1, 4, 9], [9, 20, 30], [1, 4, 9]]
[[10, 18, 24], [20, 36, 48], [10, 18, 24]]


In [12]:
print(np.array((matrix1 * matrix2).matrix))
print()
print(np.array(matrix1.matrix) * np.array(matrix2.matrix))

[[ 1  4  9]
 [ 9 20 30]
 [ 1  4  9]]

[[ 1  4  9]
 [ 9 20 30]
 [ 1  4  9]]


In [11]:
matrix = Matrix([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
matrix.ortohonalize()

AttributeError: type object 'Matrix' has no attribute 'vector_multiply'